swagger: "3.0"
info:
  description: "Evento: Objetos Canonicos TouresBalon"
  version: "1.0.0"
  title: "Evento"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

definitions:
  Pais:
    type: "object" 
    properties:
      id: 
        type: "integer"
        format: "int32"
      nombre:
        type: "string"
    xml:
      name: "Pais"  
  Ciudad:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      nombre:
        type: "string"
      pais:
        $ref: '#/definitions/Pais'
    xml:
      name: "Ciudad"
  TipoEvento:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      nombre:
        type: "string"
    xml:
      name: "TipoEvento"
  Evento:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      tipoEvento:
        $ref: '#/definitions/TipoEvento'
      ciudad:
        $ref: '#/definitions/Ciudad'
      fechaInicio:
        type: "string"
        format: "date-time"
      fechaFin:
        type: "string"
        format: "date-time"
      descripcion:
        type: "string"
    xml:
      name: "Evento"