export class Campana{
idCampanna:number;
   producto:{  
      idProducto:number;
      tipoProducto:{  
         idTipoProducto:null;
         estadoTipoProducto:{  
            idEstadoTipoProducto:number;
            estado:String;
            tipoProductos:[  
                { 
                }
            ];
            inicio:Number;
            cuantos:Number;
         };
         nombre:String;
         productos:[  
            { 
            }
         ];
         inicio:Number;
         cuantos:Number
      };
      nombreProducto:String;
      fechaSalida:Date;
      fechaLlegada:Date;
      campannas:[  
        { 
        }
      ];
      detalleOrdenCompras:[  
        { 
        }
      ];
      imagenProductos:[  
         {  
            idImagenProducto:Number;
            producto:String;
            imagen:String;
            esprincipal:Number;
            inicio:Number;
            cuantos:Number;
         }
      ];
      auditoriaVentases:[ 
        { 
        }
      ];
      inicio:Number;
      cuantos:Number;
   };
   nombreCampanna: String;
   fechaCampanna:Date;
   fechaVencimeinto:Date;
   inicio:Number;
   cuantos:Number;
}