export class Tarifa{  
    boleteriaDTO:{  
        fecha:Date;
        id:Number;
        localidad:String;
        moneda:String;
        productoId:Number;
        tiquetes:Number;
        valor:Number;
    };
    itinerarioDTOlist:[  
        {  
            idCiudad:{  
            idCiudad:Number;
            idPais:{  
                idPais:Number;
                nombre:String;
            };
            nombre:String;
            };
            idHospedaje:{  
            estrellas:Number;
            habitacionList:[  
                {  
                    idHabitacion:Number;
                    idHospedaje:Number;
                    idTipoHabitacion:{  
                        idTipoHabitacion:Number;
                        tipo:String;
                    };
                    imagenHabitacionList:[  
                        {  
                        esprincipal:Number;
                        idHabitacion:Number;
                        idImagenHabitacion:Number;
                        imagen:String;
                        }
                    ];
                    numero:Number;
                    tarifaHospedajeDTO:{  
                        fechaVigencia:Date;
                        idTarifaHospedaje:Number;
                        precio:Number;
                    }
                }
            ];
            idCiudad:{  
                idCiudad:Number;
                idPais:{  
                    idPais:Number;
                    nombre:String;
                };
                nombre:String;
            };
            idHospedaje:Number;
            imagenHospedajeList:[  
                {  
                    esprincipal:Number;
                    idHospedaje:Number;
                    idImagenHospedaje:Number;
                    imagen:String;
                }
            ];
            nombre:String;
            };
            idItinerario:Number;
            idProducto:Number;
            rutaDTO:{  
            descripcion:String;
            idCiudadDestino:{  
                idCiudad:Number;
                idPais:{  
                    idPais:Number;
                    nombre:String;
                };
                nombre:String;
            };
            idCiudadOrigen:{  
                idCiudad:Number;
                idPais:{  
                    idPais:Number;
                    nombre:String;
                };
                nombre:String;
            };
            idEmpresa:{  
                idEmpresa:Number;
                nombre:String;
                urlEndpoint:String;
            };
            idRuta:Number;
            traifaTransporteDTO:{  
                fechaVigencia:Date;
                idTarifaTransporte:Number;
                precio:Number;
            }
            }
        }
    ];
    total:Number;
 }