//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD
    {
        public int? ID_DETALLE_SOLICITUD { get; set; }
        public Nullable<int> NO_SOLICITUD { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    }
}
