//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int? NO_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public Nullable<int> ID_ESTADO_SOLICITUD { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    }
}
