//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public long noOrden { get; set; }
        public EstadoOrdenCompra estadoOrdenCompra { get; set; }
        public string fechaCreacion { get; set; }
        public string fechaVencimiento { get; set; }
        public int numeroSolicitud { get; set; }
        public double valorTotal { get; set; }
        public List<DetalleOrdenCompra> detalleOrdenCompras { get; set; }

        public class EstadoOrdenCompra
        {
            public int idEstadoOrdenCompra { get; set; }
            public string estado { get; set; }
        }

        public class TipoProducto
        {
            public int idTipoProducto { get; set; }
            public string nombre { get; set; }
        }

        public class ImagenProducto
        {
            public int idImagenProducto { get; set; }
            public string imagen { get; set; }
            public int esprincipal { get; set; }
        }

        public class Producto
        {
            public int idProducto { get; set; }
            public TipoProducto tipoProducto { get; set; }
            public string nombreProducto { get; set; }
            public string fechaSalida { get; set; }
            public string fechaLlegada { get; set; }
            public List<ImagenProducto> imagenProductos { get; set; }
        }

        public class DetalleOrdenCompra
        {
            public int idDetalleOrden { get; set; }
            public Producto producto { get; set; }
            public double valor { get; set; }
        }        
    }
}
