//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int numerosolicitud { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<System.DateTime> fechavencimiento { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string noorden { get; set; }
        public int estadoordencompraid { get; set; }
        public Nullable<int> detalleordencompras { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual DETALLESOLICITUD DETALLESOLICITUD { get; set; }
        public virtual ESTADOSOLICITUD ESTADOSOLICITUD { get; set; }
    }
}
