//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolicitudWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class touresbalonEntities2 : DbContext
    {
        public touresbalonEntities2()
            : base("name=touresbalonEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IMAGENPRODUCTO> IMAGENPRODUCTO { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPOPRODUCTO> TIPOPRODUCTO { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<DETALLESOLICITUD> DETALLESOLICITUD { get; set; }
        public DbSet<ESTADOSOLICITUD> ESTADOSOLICITUD { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
    }
}
